version: '3.10'
services:  
  mongodb:
    image: mongo:7
    container_name: ${CONTAINER_PREFIX}_mongodb_summery
    restart: always
    ports:
      - 27017:27017
    networks:
      - app-network  
networks:
  app-network:
    driver: bridge      